artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/campusx-official/100-days-of-deep-learning/raw/main/day3/placement.csv
  local_data_file: artifacts/data_ingestion/placement.csv